### ISSUE TITLE
Time Series Modeling

### ISSUE THREAD

**Issue by KeshavGautam77** [Subashcoder/Price_Prediction_and_Optimization#10]
Task 13: Time Series Modeling (ARIMA, Holt-Winters)
Task 14: Deep Learning Models (Unidirectional LSTM, Causal Transformers)
Task 16: Model Evaluation (in collaboration with Group 5)

**Comment by Prabhsimran18** [comment]
Tried models LSTM, ARIMA, Holt-Winter but due to not sufficient data for each listing across a timeline like days, months; the time series models were not effective.
