### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by Subashcoder** [Subashcoder/Price_Prediction_and_Optimization#4]
- Handle missing data using appropriate imputation techniques.
- Detect and remove outliers using statistical methods (Z-score, IQR).
- Remove duplicates and irrelevant entries.

**Comment by Nischal156** [comment]
- Removed unwanted null values (Perform statistics before removing it)
- Apply IQR and Box plot to identify the outliers (price accepted range: 0-$1000)
- But under further analysis we decided to keep the outliers
- Change the data type (amenities was in string convert to list for count analysis, change the Date type, str-> numerical, str->boolean
- drop the low correlated features
