### ISSUE TITLE
Exploratory Data Analysis (EDA) 

### ISSUE THREAD

**Issue by Subashcoder** [Subashcoder/Price_Prediction_and_Optimization#6]
- Calculate descriptive statistics.
- Visualize data distributions (scatter plots, histograms, box plots).
- Identify correlations between features.
-

**Comment by KeshavGautam77** [comment]
- Price range analysis: 80% of data lies in the range of 50-400$.
- Room_type and property_type analysis: most of the rooms are shared and house
- Box plot and Q1-Q3 analysis suggest that listing above 1000 are outliers but by performing further analysis those value can't be drop as this will unable  our model to predict listing price above 1000$.
- Common amunities analysis

**Comment by Subashcoder** [comment]
**Outliers Analysis**

- price range from 100 to 10,000 and only 0.6% of listings priced above 1500 (consider outliers ?). 
- However, the decision to classify them as outliers was denied
- Instead of removing them, consider using modeling techniques that can handle outliers or skewed distributions better, such as:
Robust regression methods (like Huber or RANSAC regression) that are less sensitive to outliers.
Tree-based models (like Random Forest or Gradient Boosting) which are less affected by the scale of target values.
Transformations: If the data distribution is skewed, you can apply transformations (like log or square root) to stabilize variance and reduce the impact of extreme values.
Separate Models: Consider building separate models for different price segments if they have distinct behaviors and characteristics.
Feature Engineering: Create features that capture the price range (e.g., price categories or bins) to retain the information without treating them as direct numerical targets.

**Comment by Subash049** [comment]
**Data Wrangling**
- Perform the location base analysis
- Used the python pandas profiling to gain insight over the data and data type. (Most of the data are in the numerical and Boolean form are can be represented as one)
- Expensive location analysis
