### ISSUE TITLE
Dashboard Development

### ISSUE THREAD

**Issue by Subashcoder** [Subashcoder/Price_Prediction_and_Optimization#7]
- Design an interactive dashboard using Tableau or Power BI.
- Include key visualizations (maps, charts, filters).
- Ensure real-time data updates if possible.
-

**Comment by KeshavGautam77** [comment]
[AirBnb price dashboard analysis  and Insights.docx](https://github.com/user-attachments/files/17388284/AirBnb.price.dashboard.analysis.and.Insights.docx)
This is our final dashboard
